=== Dayanna-BS/PlaniDecor/agenda.dtd
<!-- Debe contener solo números -->
<!ELEMENT AgendaClientes (cliente+)>
<!ELEMENT cliente (Nombre, Telefono, Email, Evento, Ciudad, Direccion)>
<!ATTLIST cliente id ID #REQUIRED>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Telefono (#PCDATA)> <!-- Debe contener solo números -->
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Evento (#PCDATA)>
<!ELEMENT Ciudad (#PCDATA)>
<!ELEMENT Direccion (#PCDATA)>

=== Dayanna-BS/PlaniDecor/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<?xml-stylesheet type="text/xsl" href="agenda.xsl"?>
<AgendaClientes>
<cliente id="T7777">

 <Nombre>Thiago Calderon</Nombre>
 <Telefono>"615802493"</Telefono>
 <Email>thiago@gmail.com</Email>
 <Evento>Cumplea√±os</Evento>
 <Ciudad>Sevilla</Ciudad>
 <Direccion>Calle Los justicieros 360</Direccion>
 </cliente>

 <cliente id="L8888">
 <Nombre>Lupita Zevallos</Nombre>
 <Telefono>"615802477"</Telefono>
 <Email>lupita@gmail.com</Email>
 <Evento>Boda</Evento>
 <Ciudad>Madrid</Ciudad>
 <Direccion>Calle Atlantico 82</Direccion>
</cliente>

</AgendaClientes>
